### ISSUE TITLE
Can't add new configurations to the config.ini

### ISSUE THREAD

**Issue by mindexman** [kepmehz/RDR3PoolExtender#1]
I am trying to add <aiTextureMaxMem_3_Base value="xxxxx"/> value from gameconfig.xml file to config.ini file, however it doesn't seem to be working. If you could provide some information or guidance on how do it I would greatly appreciate it

**Comment by kepmehz** [comment]
aiTextureMaxMem_3_Base is not a game pool therefore you can't extend it with this tool.
